Check action token

diff --git a/.github/workflows/report_analysis.yaml b/.github/workflows/report_analysis.yaml
--- a/.github/workflows/report_analysis.yaml
+++ b/.github/workflows/report_analysis.yaml
@@ -7,6 +7,17 @@ jobs:
     name: Code Analysis
     runs-on: DMAHostRunner
     steps:
+      - name: Check git tokens
+        run: |
+          if [ -z "${CODACY_PROJECT_TOKEN}" ]; then
+            echo "Error: CODACY_PROJECT_TOKEN is not set"
+            exit 1
+          fi
+          if [ -z "${CODECOV_TOKEN}" ]; then
+            echo "Error: CODECOV_TOKEN is not set"
+            exit 1
+          fi
+
       - name: Checkout code
         uses: actions/checkout@main
 
